# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    # job filter, but it doesn't work for
    # PRs (into the filtered branches).
    #branches:
    #  only:
    #    - test
    #    - master
    #    - dev
    environment:
      - ONLY_BRANCHES: "test master dev"
    docker:
      - image: circleci/python
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: long test
          command: |
            if bash ./tests/filterBranch.sh ; then
              # your tests go here
              sleep 123
            fi

# workflow filter, but it doesn't work for
# PRs (into the filtered branches).

#workflows:
#  version: 2
#  all:
#    jobs:
#      - build:
#          filters:
#            branches:
#              only:
#                - test
#                - master
#                - dev
