# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    # job filter, but it doesn't work for
    # PRs (into the filtered branches).
    # We use ONLY_BRANCHES and filterBranch.sh instead
    #branches:
    #  only:
    #    - test
    #    - master
    #    - dev
    environment:
      - ONLY_BRANCHES: "test master dev"
    docker:
      - image: circleci/python
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: long test
          command: |
            if bash ./tests/filterBranch.sh ; then
              echo "running tests!"
              echo

              #todo: your tests go here
              #todo: remove sleep
              echo "Sleep for a little bit"
              sleep 22

              echo
              echo "tests complete!"
            else
              echo "skipping tests!"
            fi

# workflow filter, but it doesn't work for
# PRs (into the filtered branches).
# We use ONLY_BRANCHES and filterBranch.sh instead
#workflows:
#  version: 2
#  all:
#    jobs:
#      - build:
#          filters:
#            branches:
#              only:
#                - test
#                - master
#                - dev
