# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    environment:
      - ONLY_BRANCHES: "test master dev"
    docker:
      - image: circleci/python
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: long test
          command: sleep 123

# traditional way of doing this is with workflows, but that
# doesn't work for PRs into the filtered branches.

#workflows:
#  version: 2
#  all:
#    jobs:
#      - build:
#          filters:
#            branches:
#              only:
#                - test
#                - master
#                - dev
